from:
  folder: examples
  format: md
to:
  folder: examples
  format: html
schema: title_block.json
merge: false
strict: true
options:
  latex-engine: xelatex
variables:
  documentclass: article
filters:
  - behead2.hs
