language: haskell
rvm:
- 1.9.3
- 2.1.2
install:
- travis_retry cabal install pandoc pandoc-citeproc
- travis_retry bundle install
script:
- bundle exec rake
- bundle exec rakali convert .rakali.yml
- bundle exec rake repo:push
deploy:
  provider: rubygems
  api_key:
    secure: Gcr3lbeTuQW0MXpO9sh2lnYN4EY9FFLaBhF9RK99JjGUYAm7HR70yWM/EhAThWtfjVhzwcjzOJ6RrGE401zVRUsye8GTMXA5d7USx1KGGmWNRG5cYTCBWhymHXv4vfSfMp3CP2FgyfcTigXu8yHh18ONpHIhbBuZNx1DliBEPgU=
  gem: rakali
  on:
    tags: true
    repo: rakali/rakali.rb
env:
  global:
  - secure: hO+7d+PxnOAk0tLbJOSisF6aKzGjll6E3TsaMuZHoBAA93WCvpZgYmn5VyJy1eRCobxqeP/7xIfiCHBMzHNtr7BC4wHMWx+z6tE/M3osTwQVVsg8Cdviq4LU/XvgXjk4dI8Owsk2aEC/Dw2uRm3XBmvnpMwrj3QoNjunCUeXwo4=
  - secure: JCEDpRmeSeR3nqJg3659mXafpjyvHG5jdg5Uk54zdb/jQfDoHX7qHO5bPG0IJTAKx+vnVWpcs6JMC6ADocymaMxv195Acu9Ch3IEjcYBwdZFoqbBC7d5ZgmhloAVrWBAWgT9zoOj7ppiO3U2iUuj/vHOL57Nnf/DCkW4oxB6ykU=
  - secure: MLmk4mLBqOK8rDbYaT+IZnP0IoxLueCWTGwoNpyx2HdcUIny2235iCmJGE66FY0/ULFsQ3WmFuB5OWgRGkj1bvYAOFiucWotZzDnsUrWyGcH+ZL4xBaZuP9qEFedtB7r1Dv9nrBn6CuhLi1l+BJwk01PpPVq0UPWXxTQ8f9wbhI=
